//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCommunity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleTask
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Description { get; set; }
        public decimal Budget { get; set; }
        public bool Status { get; set; }
        public Nullable<int> CommunityId { get; set; }
        public Nullable<int> MemberId { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual Member Member { get; set; }
    }
}
